// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0y9-8IcwuWEdQM53uWdDPBy5WTFVpRU',
    appId: '1:155276331185:web:e484dafcd6527c154ffa90',
    messagingSenderId: '155276331185',
    projectId: 'shasha-shop',
    authDomain: 'shasha-shop.firebaseapp.com',
    storageBucket: 'shasha-shop.appspot.com',
    measurementId: 'G-M2P1LFPQ31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJ5eZYx9brCwm3hjWW5zyjGWrYR1i6DQ',
    appId: '1:155276331185:android:693ca34274c312fc4ffa90',
    messagingSenderId: '155276331185',
    projectId: 'shasha-shop',
    storageBucket: 'shasha-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKFyBDWNnIrDjTwyyvjPC3ltIa6WG1bv8',
    appId: '1:155276331185:ios:7d4a3502ea823d9e4ffa90',
    messagingSenderId: '155276331185',
    projectId: 'shasha-shop',
    storageBucket: 'shasha-shop.appspot.com',
    iosBundleId: 'com.example.architexturePattern',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKFyBDWNnIrDjTwyyvjPC3ltIa6WG1bv8',
    appId: '1:155276331185:ios:7d4a3502ea823d9e4ffa90',
    messagingSenderId: '155276331185',
    projectId: 'shasha-shop',
    storageBucket: 'shasha-shop.appspot.com',
    iosBundleId: 'com.example.architexturePattern',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0y9-8IcwuWEdQM53uWdDPBy5WTFVpRU',
    appId: '1:155276331185:web:7eed4aa4899a762b4ffa90',
    messagingSenderId: '155276331185',
    projectId: 'shasha-shop',
    authDomain: 'shasha-shop.firebaseapp.com',
    storageBucket: 'shasha-shop.appspot.com',
    measurementId: 'G-PFCN6T3PCW',
  );
}
